### ISSUE TITLE
[Suggestion] Use Nord Color Scheme

### ISSUE THREAD

**Issue by Bad3r** [natsustan/logseq-reflect-theme#1]
Hey there!
I just tried them out, and I like the design, but I have to say the color choice for the dark background is off-putting on non-OLED monitors. If you are open to changing the default color theme, I recommend considering the Nord scheme:
https://www.nordtheme.com/

**Comment by Bad3r** [comment]
![image](https://user-images.githubusercontent.com/25513724/225377417-ed33fb51-3356-4748-9159-c552954004a6.png)

**Comment by Bad3r** [comment]
Here is the same page using Nord scheme colors (my custom version of Dev theme)
![image](https://user-images.githubusercontent.com/25513724/225483897-dba9ac74-fbfe-4a63-b8ef-9db9da222a68.png)

**Comment by natsustan** [comment]
That's a great suggestion, thank you for sharing it. I just tested it on my MacBook. I've also noticed that dark mode doesn't always stand out on LCD screens. Personally, I'm a fan of the Nord theme and have even used it in my terminal before. I'll definitely be on the lookout for improved color schemes and display options to enhance your experience.

By the way, if you're not using the whiteboard function, you can turn it off. This will reveal a search bar that I designed originally.

**Comment by Bad3r** [comment]
oh, that's nice. Unfortunately, I do use whiteboards. It's a great feature! but I'll try it out.

I am considering creating a Nord theme for Logseq. I have been waiting for someone to make one for a while :sweat_smile: 

site-note: Good to close
![code](https://cdn.unsigned.sh/logseq_nord_code.png)

![https://cdn.unsigned.sh/logseq_nord_demo.png](https://cdn.unsigned.sh/logseq_nord_demo.png)

![https://cdn.unsigned.sh/logseq_nord_pdf.png](https://cdn.unsigned.sh/logseq_nord_pdf.png)

**Comment by Bad3r** [comment]
You can test the theme here: https://github.com/bad3r/logseq-Nord-Theme  
it's not available in the marketplace yet.
