### ISSUE TITLE
Emoji Display

### ISSUE THREAD

**Issue by 1xdali** [natsustan/logseq-reflect-theme#2]
There are some issues with supporting emojis. I don't know if it's because of the font or some other reason.

For example: 1⃣️ 2⃣️ 3⃣️
<img width="507" alt="截屏2023-03-28 11 55 54" src="https://user-images.githubusercontent.com/29502440/228124153-257d8b2f-e1c3-406d-baf0-d3964cb9a63e.png">

**Comment by natsustan** [comment]
感谢您的 Issue。我发现我用的 `Inter` 字体对这这种 keycap 的 Emoji 支持的不好...
我看了 Logseq 现在的网页代码，没办法对 Emoji 单独做区分（可能是我不行）...
所以，如果你想要恢复展示 Emoji，请在您的 `custom.css` 中添加
```
:root {
  --font-sans: ui-sans-serif, system-ui, -apple-system, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol, Noto Color Emoji;
 }
 ```
 使其字体改为系统字体或者改为你喜欢的字体（我觉得苹方的效果已经很好了）。我将在后续在研究如何兼容这些 Emoji！

**Comment by 1xdali** [comment]
谢谢您的方案
