### ISSUE TITLE
Suggestion: A more obvious block embed

### ISSUE THREAD

**Issue by jenningsb2** [natsustan/logseq-reflect-theme#4]
Currently, block embeds don't have the background to distinguish them from other content, making it hard to distinguish a normal block from an embedded one. 

All good if this is intentional—just a suggestion!

**Comment by natsustan** [comment]
Hey Bailey

**Comment by natsustan** [comment]
Hey Bailey, I definitely won't tell you that I haven't used the block embed feature before you told me. XD 

I just simply wanted to modify the color of the linked reference area.

Now I have fixed it and given it a background color. Hope you like it.
